version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  wedding-ui: # name of the first service
    build: wedding-ui # specify the directory of the Dockerfile
    ports:
      - "3000:3000" # specify port forewarding

  wedding-server: #name of the second service
    build: wedding-server # specify the directory of the Dockerfile
    ports:
      - "4000:4000" #specify ports forewarding

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding